import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'MENUITEMS.MAIN.TEXT',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
  },

  // Admin Modules
  {
    path: '/admin/dashboard/main',
    title: 'MENUITEMS.DASHBOARD.TEXT',
    iconType: 'feather',
    icon: 'monitor',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.PROJECTS.TEXT',
    iconType: 'feather',
    icon: 'book',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],

    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
      {
        path: '/admin/projects/allProjects',
        title: 'MENUITEMS.PROJECTS.LIST.ALL-PROJECTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
      },
      {
        path: '/admin/projects/addProject',
        title: 'MENUITEMS.PROJECTS.LIST.ADD-PROJECT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
      },
    
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.EMPLOYEES.TEXT',
    iconType: 'feather',
    icon: 'users',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
      {
        path: '/admin/employees/allEmployees',
        title: 'MENUITEMS.EMPLOYEES.LIST.ALL-EMPLOYEE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
      },
      {
        path: '/admin/employees/add-employee',
        title: 'MENUITEMS.EMPLOYEES.LIST.ADD-EMPLOYEE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
      },
      {
        path: '/admin/employees/bde-employee',
        title: 'BDE Employee',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
      },
      
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.LEAVES.TEXT',
    iconType: 'feather',
    icon: 'trello',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
      {
        path: '/admin/leaves/leave-requests',
        title: 'MENUITEMS.LEAVES.LIST.LEAVE-REQUESTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
      },
      {
        path: '/admin/leaves/leave-balance',
        title: 'MENUITEMS.LEAVES.LIST.LEAVE-BALANCE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
        submenu: [],
      },
    
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.HOLIDAYS.TEXT',
    iconType: 'feather',
    icon: 'coffee',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
      {
        path: '/admin/holidays/all-holidays',
        title: 'MENUITEMS.HOLIDAYS.LIST.ALL-HOLIDAYS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
        submenu: [],
      },
     
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.ATTENDANCE.TEXT',
    iconType: 'feather',
    icon: 'edit',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
      {
        path: '/admin/attendance/today',
        title: 'MENUITEMS.ATTENDANCE.LIST.TODAY',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
        submenu: [],
      },
      {
        path: '/admin/attendance/employee-attendance',
        title: 'Employee Attendance',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
        submenu: [],
      },
      {
        path: '/admin/attendance/attendance-sheet',
        title: 'MENUITEMS.ATTENDANCE.LIST.SHEET',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.CLIENTS.TEXT',
    iconType: 'feather',
    icon: 'user',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
      {
        path: '/admin/clients/all-clients',
        title: 'MENUITEMS.CLIENTS.LIST.ALL-CLIENTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
        submenu: [],
      },
      
    ],
  },
  
  {
    path: '',
    title: 'MENUITEMS.PAYROLL.TEXT',
    iconType: 'feather',
    icon: 'clipboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
      {
        path: '/admin/payroll/employee-salary',
        title: 'MENUITEMS.PAYROLL.LIST.EMPLOYEE_SALARY',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
        submenu: [],
      },
     
    ],
  },

 
  {
    path: '/admin/daily-update',
    title: 'Daily Update',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
  },
  {
    path: '/admin/departments',
    title: 'Departments',
    iconType: 'feather',
    icon: 'layers',
    class: '',
    groupTitle: false,
    badge: '', badgeClass: '', role: ['Admin'], submenu: [],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
  },
  {
    path: '/admin/alltasks',
    title: 'Tasks',
    iconType: 'feather',
    icon: 'command',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
  },
  {
    path: '',
    title: 'BDE Analytics',
    iconType: 'feather',
    icon: 'bar-chart-2',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
      {
        path: '/admin/kpi/bde-targets',
        title: 'BDE Targets',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
      },
      {
        path: '/admin/kpi/bde-analytics',
        title: 'BDE Performance',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
      },
    ],
  },
 
  {
    path: '/employee/dashboard',
    title: 'MENUITEMS.EMPLOYEE.DASHBOARD',
    iconType: 'feather',
    icon: 'airplay',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
  },
  {
    path: '',
    title: 'MENUITEMS.ATTENDANCE.TEXT',
    iconType: 'feather',
    icon: 'edit',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
      {
        path: '/employee/attendance',
        title: 'MENUITEMS.EMPLOYEE.ATTENDANCE',
        iconType: 'feather',
        icon: 'edit',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
        submenu: [],
      },
      {
        // path: '/employee/attendance/employee-attendance',
        path: '/admin/attendance/employee-attendance',
        title: 'Employee Attendance',
        iconType: 'feather',
        icon: 'user-check',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR'],
        submenu: [],
      },
      {
        path: '/admin/attendance/today',
        title: 'Today Attendance',
        iconType: 'feather',
        icon: 'user-check',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR'],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.LEAVES.TEXT',
    iconType: 'feather',
    icon: 'trello',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
      {
        path: '/employee/myleaves',
        title: 'MENUITEMS.LEAVES.LIST.LEAVE-REQUESTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        submenu: [],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
      },
      {
        path: '/employee/myleaves/leave-balance',
        title: 'MENUITEMS.LEAVES.LIST.LEAVE-BALANCE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
        submenu: [],
      },
      {
        path: '/employee/myleaves/employee-leaves',
        title: 'Employee Leaves ',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR'],
        submenu: [],
      },
    ]
  },
  
  {
    path: '',
    title: 'Employees',
    iconType: 'feather',
    icon: 'users',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['employee'],
    department: ['HR'],
    submenu: [
      {
        path: '/employee/employee-list/allEmployees',
        title: 'All Employees ',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
        department: ['HR'],
      },
      {
        path: '/employee/employee-list/add-employee',
        title: 'Add Employee',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
        department: ['HR'],
      },
      {
        path: '/employee/employee-list/bde-employee',
        title: 'BDE Employees ',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
        department: ['HR'],
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.HOLIDAYS.TEXT',
    iconType: 'feather',
    icon: 'coffee',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['HR'],
    submenu: [
      {
        path: '/employee/holidays/all-holidays',
        title: 'MENUITEMS.HOLIDAYS.LIST.ALL-HOLIDAYS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR'],
        submenu: [],
      },
    ],
  },
  {
    path: '/employee/myteam',
    title: 'MENUITEMS.EMPLOYEE.MYTEAM',
    iconType: 'feather',
    icon: 'users',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
    department: ['BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
  },
  {
    path: '/employee/myprojects',
    title: 'MENUITEMS.EMPLOYEE.MYPROJECTS',
    iconType: 'feather',
    icon: 'database',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
    department: ['BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],

  },
  {
    path: '/employee/mytasks',
    title: 'MENUITEMS.EMPLOYEE.MYTASKS',
    iconType: 'feather',
    icon: 'command',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
    department: ['BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],

  },
  {
    path: '',
    title: 'MENUITEMS.PAYROLL.TEXT',
    iconType: 'feather',
    icon: 'clipboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['HR'],
    // department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
      {
        path: '/employee/payroll/employee-salary',
        title: 'MENUITEMS.PAYROLL.LIST.EMPLOYEE_SALARY',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        department: ['HR'],
        // department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
        submenu: [],
      },

    ],
  },
  {
    path: '',
    title: 'MENUITEMS.PAYROLL.TEXT',
    iconType: 'feather',
    icon: 'clipboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    // department: ['HR'],
    department: ['Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
      {
        path: '/employee/payroll/employee-salary',
        title: 'MENUITEMS.PAYROLL.LIST.SALARY',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        department: ['Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
        submenu: [],
      },

    ],
  },
  {
    path: '/employee/daily-update',
    title: 'Daily Update',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [
      {
        path: '/employee/daily-update',
        title: 'My Daily Update',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        submenu: [],
        department: ['HR'],
      },
      {
        path: '/employee/daily-update/all-employees',
        title: 'All Employees Updates',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        submenu: [],
        department: ['HR'],
      },
    ],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],

  },
  {
    path: '/employee/departments',
    title: 'Departments',
    iconType: 'feather',
    icon: 'layers',
    class: '',
    groupTitle: false,
    badge: '', badgeClass: '', role: ['Employee'], submenu: [],
    department: ['HR'],
  },
  {
    path: '/employee/alltasks',
    title: 'All Task',
    iconType: 'feather',
    icon: 'command',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],

  },
  
  {
    path: 'client/dashboard',
    title: 'MENUITEMS.CLIENT.DASHBOARD',
    iconType: 'feather',
    icon: 'airplay',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BDE'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },


  
  {
    path: '',
    title: 'MENUITEMS.CLIENTS.TEXT',
    iconType: 'feather',
    icon: 'user',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BDE'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
      {
        path: '/client/clients/all-clients',
        title: 'MENUITEMS.CLIENTS.LIST.ALL-CLIENTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
        submenu: [],
      },
      {
        path: '/client/clients/add-client',
        title: 'MENUITEMS.CLIENTS.LIST.ADD-CLIENT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
        submenu: [],
      },
   
    ],
  },
  
  {
    path: '',
    title: 'MENUITEMS.LEAVES.TEXT',
    iconType: 'feather',
    icon: 'trello',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BDE'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
      {
        path: '/client/myLeave',
        title: 'MENUITEMS.LEAVES.LIST.LEAVE-REQUESTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['BDE'],
        submenu: [],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
      },
      {
        path: '/client/leave-balance',
        title: 'MENUITEMS.LEAVES.LIST.LEAVE-BALANCE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['BDE'],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
        submenu: [],
      },
    ]
  },
  {
    path: '/client/attendance',
    title: 'MENUITEMS.EMPLOYEE.ATTENDANCE',
    iconType: 'feather',
    icon: 'edit',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BDE'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },
  {
    path: '/client/myteam',
    title: 'Team',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BDE'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },
  {
    path: '/client/daily-update',
    title: 'Daily Update',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BDE'],
    submenu: [],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],

  },
  {
    path: '/client/employee-updates',
    title: 'Employee Updates',
    iconType: 'feather',
    icon: 'activity',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BDE'],
    submenu: [],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
  },
  {
    path: '',
    title: 'MENUITEMS.PAYROLL.TEXT',
    iconType: 'feather',
    icon: 'clipboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BDE'],
    // department: ['HR'],
    department: ['BDE'],
    submenu: [
      {
        path: '/client/payroll/employee-salary',
        title: 'MENUITEMS.PAYROLL.LIST.SALARY',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        // department: ['HR'],
        department: ['BDE'],
        submenu: [],
      },

    ],
  },
 
  // BA Modules
  {
    path: '/ba/dashboard/main',
    title: 'Dashboard',
    iconType: 'feather',
    icon: 'monitor',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BA'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },
  {
    path: '',
    title: 'Clients',
    iconType: 'feather',
    icon: 'user',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BA'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
      {
        path: '/ba/clients/all-clients',
        title: 'All Clients',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
      },
    ],
  },
  {
    path: '',
    title: 'Leave Management',
    iconType: 'feather',
    icon: 'trello',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BA'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
      {
        path: '/ba/myleaves',
        title: 'My Leaves',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
      },
      {
        path: '/ba/myleaves/leave-balance',
        title: 'Leave Balance',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
      },
    ],
  },
  {
    path: '/ba/attendance',
    title: 'Attendance',
    iconType: 'feather',
    icon: 'edit',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BA'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },
  {
    path: '/ba/employees/allEmployees',
    title: 'Team',
    iconType: 'feather',
    icon: 'users',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BA'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },
  {
    path: '/ba/daily-update',
    title: 'Daily Update',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BA'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },
  {
    path: '/ba/employee-updates',
    title: 'Employee Updates',
    iconType: 'feather',
    icon: 'activity',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BA'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },
  {
    path: '/ba/payroll/employee-salary',
    title: 'Payroll',
    iconType: 'feather',
    icon: 'clipboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BA'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },
  {
    path: '',
    title: 'Projects',
    iconType: 'feather',
    icon: 'book',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BA'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
      {
        path: '/ba/projects/allProjects',
        title: 'All Projects',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
      },
      {
        path: '/ba/projects/addProject',
        title: 'Add Project',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
      },
    ],
  },
  {
    path: '/ba/alltasks',
    title: 'Tasks',
    iconType: 'feather',
    icon: 'command',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BA'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },

  // BDE Projects & Tasks
  {
    path: '',
    title: 'Projects',
    iconType: 'feather',
    icon: 'book',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BDE'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [
      {
        path: '/client/projects/allProjects',
        title: 'All Projects',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
      },
      {
        path: '/client/projects/addProject',
        title: 'Add Project',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
        department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
      },
    ],
  },
  {
    path: '/client/alltasks',
    title: 'Tasks',
    iconType: 'feather',
    icon: 'command',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BDE'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },
  {
    path: '/client/performance',
    title: 'My Performance',
    iconType: 'feather',
    icon: 'bar-chart-2',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BDE'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },
  {
    path: '/client/my-targets',
    title: 'My Targets',
    iconType: 'feather',
    icon: 'target',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BDE'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },
  {
    path: '/client/daily-notes',
    title: 'Daily Client Notes',
    iconType: 'feather',
    icon: 'edit-3',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BDE'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },

  // Login Page Settings (Admin & HR only)
  {
    path: '/admin/login-settings',
    title: 'Login Page Settings',
    iconType: 'feather',
    icon: 'image',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },
  {
    path: '/employee/login-settings',
    title: 'Login Page Settings',
    iconType: 'feather',
    icon: 'image',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['HR'],
    submenu: [],
  },

  // Common Modules

  {
    path: '',
    title: 'Apps',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },
  {
    path: 'calendar',
    title: 'Calendar',
    iconType: 'feather',
    icon: 'calendar',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: 'badge bg-blue sidebar-badge float-end',
    role: ['Admin', 'Employee', 'BDE', 'BA'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },
  {
    path: '/chat-window',
    title: 'Chat',
    iconType: 'feather',
    icon: 'message-square',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin', 'Employee', 'BDE', 'BA'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
    newTab: true,
  },
  {
    path: 'task',
    title: 'Task',
    iconType: 'feather',
    icon: 'check-circle',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin', 'BA', 'BDE'],
    department: ['HR', 'BDE', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },
  
];
