import { RouteInfo } from './sidebar.metadata';

export const ROUTES: RouteInfo[] = [
  // ============================================================
  // ADMIN MODULES
  // ============================================================

  {
    path: '',
    title: 'MENUITEMS.MAIN.TEXT',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: [],
    submenu: [],
  },

  {
    path: '/admin/dashboard/main',
    title: 'MENUITEMS.DASHBOARD.TEXT',
    iconType: 'feather',
    icon: 'monitor',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: [],
    submenu: [],
  },

  {
    path: '',
    title: 'MENUITEMS.PROJECTS.TEXT',
    iconType: 'feather',
    icon: 'book',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: [],
    submenu: [
      {
        path: '/admin/projects/allProjects',
        title: 'MENUITEMS.PROJECTS.LIST.ALL-PROJECTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: [],
        submenu: [],
      },
      {
        path: '/admin/projects/addProject',
        title: 'MENUITEMS.PROJECTS.LIST.ADD-PROJECT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: [],
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'MENUITEMS.EMPLOYEES.TEXT',
    iconType: 'feather',
    icon: 'users',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: [],
    submenu: [
      {
        path: '/admin/employees/allEmployees',
        title: 'MENUITEMS.EMPLOYEES.LIST.ALL-EMPLOYEE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: [],
        submenu: [],
      },
      {
        path: '/admin/employees/add-employee',
        title: 'MENUITEMS.EMPLOYEES.LIST.ADD-EMPLOYEE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: [],
        submenu: [],
      },
      {
        path: '/admin/employees/bde-employee',
        title: 'BDE Employee',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: [],
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'MENUITEMS.LEAVES.TEXT',
    iconType: 'feather',
    icon: 'trello',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: [],
    submenu: [
      {
        path: '/admin/leaves/leave-requests',
        title: 'MENUITEMS.LEAVES.LIST.LEAVE-REQUESTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: [],
        submenu: [],
      },
      {
        path: '/admin/leaves/leave-balance',
        title: 'Employees Leave Balance',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: [],
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'MENUITEMS.HOLIDAYS.TEXT',
    iconType: 'feather',
    icon: 'coffee',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: [],
    submenu: [
      {
        path: '/admin/holidays/all-holidays',
        title: 'MENUITEMS.HOLIDAYS.LIST.ALL-HOLIDAYS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: [],
        submenu: [],
      },
    ],
  },

  {
    path: '/admin/interviews',
    title: 'Interviews',
    iconType: 'feather',
    icon: 'user-check',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: [],
    submenu: [],
  },

  {
    path: '',
    title: 'MENUITEMS.ATTENDANCE.TEXT',
    iconType: 'feather',
    icon: 'edit',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: [],
    submenu: [
      {
        path: '/admin/attendance/today',
        title: 'MENUITEMS.ATTENDANCE.LIST.TODAY',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: [],
        submenu: [],
      },
      {
        path: '/admin/attendance/employee-attendance',
        title: 'Employee Attendance',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: [],
        submenu: [],
      },
      {
        path: '/admin/attendance/attendance-sheet',
        title: 'MENUITEMS.ATTENDANCE.LIST.SHEET',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: [],
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'MENUITEMS.CLIENTS.TEXT',
    iconType: 'feather',
    icon: 'user',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: [],
    submenu: [
      {
        path: '/admin/clients/all-clients',
        title: 'MENUITEMS.CLIENTS.LIST.ALL-CLIENTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: [],
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'MENUITEMS.PAYROLL.TEXT',
    iconType: 'feather',
    icon: 'clipboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: [],
    submenu: [
      {
        path: '/admin/payroll/employee-salary',
        title: 'MENUITEMS.PAYROLL.LIST.EMPLOYEE_SALARY',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: [],
        submenu: [],
      },
    ],
  },

  {
    path: '/admin/daily-update',
    title: 'Daily Update',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: [],
    submenu: [],
  },

  {
    path: '/admin/departments',
    title: 'Departments',
    iconType: 'feather',
    icon: 'layers',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: [],
    submenu: [],
  },

  {
    path: '/admin/alltasks',
    title: 'Tasks',
    iconType: 'feather',
    icon: 'command',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: [],
    submenu: [],
  },

  {
    path: '',
    title: 'BDE Analytics',
    iconType: 'feather',
    icon: 'bar-chart-2',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: [],
    submenu: [
      {
        path: '/admin/kpi/bde-targets',
        title: 'BDE Targets',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: [],
        submenu: [],
      },
      {
        path: '/admin/kpi/bde-analytics',
        title: 'BDE Performance',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        department: [],
        submenu: [],
      },
    ],
  },

  {
    path: '/admin/login-settings',
    title: 'Login Page Settings',
    iconType: 'feather',
    icon: 'image',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    department: [],
    submenu: [],
  },

  // ============================================================
  // HR / EMPLOYEE MODULES
  // role = Employee
  // department = HR
  // ============================================================

  {
    path: '/employee/dashboard',
    title: 'MENUITEMS.EMPLOYEE.DASHBOARD',
    iconType: 'feather',
    icon: 'airplay',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['HR'],
    submenu: [],
  },

  {
    path: '',
    title: 'Interviews',
    iconType: 'feather',
    icon: 'user-check',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['HR', 'HR Coordinator'],
    submenu: [
      {
        path: '/employee/hr-interviews',
        title: 'All Interviews',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR', 'HR Coordinator'],
        submenu: [],
      },
      {
        path: '/employee/my-interviews',
        title: 'My Interviews',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR', 'HR Coordinator'],
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'MENUITEMS.ATTENDANCE.TEXT',
    iconType: 'feather',
    icon: 'edit',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['HR'],
    submenu: [
      {
        path: '/employee/attendance/',
        title: 'My Attendance',
        iconType: 'feather',
        icon: 'pie-chart',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR'],
        submenu: [],
      },
      {
        path: '/employee/hr-attendance/today',
        title: 'Today Attendance',
        iconType: 'feather',
        icon: 'user-check',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR'],
        submenu: [],
      },
      {
        path: '/employee/hr-attendance/employee-attendance',
        title: 'Employee Attendance',
        iconType: 'feather',
        icon: 'users',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR'],
        submenu: [],
      },
      {
        path: '/employee/hr-attendance/attendance-sheet',
        title: 'Attendance Sheet',
        iconType: 'feather',
        icon: 'file-text',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR'],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.LEAVES.TEXT',
    iconType: 'feather',
    icon: 'trello',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['HR'],
    submenu: [
      {
        path: '/employee/hr-leaves/leave-requests',
        title: 'Leave Requests',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR'],
        submenu: [],
      },
      {
        path: '/employee/hr-leaves/employee-leave-balance',
        title: 'Employees Leave Balance',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR'],
        submenu: [],
      },
      {
        path: '/employee/myleaves/leave-balance',
        title: 'MENUITEMS.LEAVES.LIST.LEAVE-BALANCE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR'],
        submenu: [],
      },
      {
        path: '/employee/myleaves/employee-leaves',
        title: 'Employee Leaves',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR'],
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'Employees',
    iconType: 'feather',
    icon: 'users',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['HR'],
    submenu: [
      {
        path: '/employee/employee-list/allEmployees',
        title: 'All Employees',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR'],
        submenu: [],
      },
      {
        path: '/employee/employee-list/add-employee',
        title: 'Add Employee',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR'],
        submenu: [],
      },
      {
        path: '/employee/employee-list/bde-employee',
        title: 'BDE Employees',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR'],
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'MENUITEMS.HOLIDAYS.TEXT',
    iconType: 'feather',
    icon: 'coffee',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['HR'],
    submenu: [
      {
        path: '/employee/holidays/all-holidays',
        title: 'MENUITEMS.HOLIDAYS.LIST.ALL-HOLIDAYS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR'],
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'MENUITEMS.PAYROLL.TEXT',
    iconType: 'feather',
    icon: 'clipboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['HR'],
    submenu: [
      {
        path: '/employee/payroll/employee-salary',
        title: 'MENUITEMS.PAYROLL.LIST.EMPLOYEE_SALARY',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['HR'],
        submenu: [],
      },
    ],
  },

  {
    path: '/employee/daily-update',
    title: 'Daily Update',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['HR'],
    submenu: [],
  },

  {
    path: '/employee/departments',
    title: 'Departments',
    iconType: 'feather',
    icon: 'layers',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['HR'],
    submenu: [],
  },

  {
    path: '/employee/alltasks',
    title: 'All Task',
    iconType: 'feather',
    icon: 'command',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['HR'],
    submenu: [],
  },

  {
    path: '/employee/login-settings',
    title: 'Login Page Settings',
    iconType: 'feather',
    icon: 'image',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['HR'],
    submenu: [],
  },

  // ============================================================
  // GENERAL EMPLOYEE MODULES
  // role = Employee
  // departments = Backend Developer, Frontend Developer, Fullstack Developer, Graphic
  // ============================================================

  {
    path: '/employee/dashboard',
    title: 'MENUITEMS.EMPLOYEE.DASHBOARD',
    iconType: 'feather',
    icon: 'airplay',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic', 'HR Coordinator'],
    submenu: [],
  },

  // Interviews assigned to a Senior developer to conduct.
  // Visibility is gated to employee_level = Senior in SidebarComponent.
  {
    path: '/employee/my-interviews',
    title: 'Interviews',
    iconType: 'feather',
    icon: 'user-check',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic', 'BDE', 'BA'],
    submenu: [],
  },

  {
    path: '',
    title: 'MENUITEMS.ATTENDANCE.TEXT',
    iconType: 'feather',
    icon: 'edit',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic', 'HR Coordinator'],
    submenu: [
      {
        path: '/employee/attendance',
        title: 'MENUITEMS.EMPLOYEE.ATTENDANCE',
        iconType: 'feather',
        icon: 'edit',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic', 'HR Coordinator'],
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'MENUITEMS.LEAVES.TEXT',
    iconType: 'feather',
    icon: 'trello',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic', 'HR Coordinator'],
    submenu: [
      {
        path: '/employee/myleaves',
        title: 'MENUITEMS.LEAVES.LIST.LEAVE-REQUESTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic', 'HR Coordinator'],
        submenu: [],
      },
      {
        path: '/employee/myleaves/leave-balance',
        title: 'MENUITEMS.LEAVES.LIST.LEAVE-BALANCE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic', 'HR Coordinator'],
        submenu: [],
      },
    ],
  },

  {
    path: '/employee/holidays/all-holidays',
    title: 'MENUITEMS.HOLIDAYS.TEXT',
    iconType: 'feather',
    icon: 'coffee',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic', 'HR Coordinator'],
    submenu: [],
  },

  {
    path: '/employee/payroll/employee-salary',
    title: 'Payroll',
    iconType: 'feather',
    icon: 'clipboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic', 'HR Coordinator'],
    submenu: [],
  },

  {
    path: '/employee/myteam',
    title: 'My Team',
    iconType: 'feather',
    icon: 'users',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic', 'HR Coordinator'],
    submenu: [],
  },

  {
    path: '/employee/myprojects',
    title: 'My Projects',
    iconType: 'feather',
    icon: 'book',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic', 'HR Coordinator'],
    submenu: [],
  },

  {
    path: '/employee/mytasks',
    title: 'My Tasks',
    iconType: 'feather',
    icon: 'check-circle',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic', 'HR Coordinator'],
    submenu: [],
  },

  {
    path: '/employee/daily-update',
    title: 'Daily Update',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic', 'HR Coordinator'],
    submenu: [],
  },

  // ============================================================
  // BDE MODULES
  // role = Employee
  // department = BDE
  // ============================================================

  {
    path: 'client/dashboard',
    title: 'MENUITEMS.CLIENT.DASHBOARD',
    iconType: 'feather',
    icon: 'airplay',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BDE'],
    submenu: [],
  },

  {
    path: '',
    title: 'MENUITEMS.CLIENTS.TEXT',
    iconType: 'feather',
    icon: 'user',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BDE'],
    submenu: [
      {
        path: '/client/clients/all-clients',
        title: 'MENUITEMS.CLIENTS.LIST.ALL-CLIENTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['BDE'],
        submenu: [],
      },
      {
        path: '/client/clients/add-client',
        title: 'MENUITEMS.CLIENTS.LIST.ADD-CLIENT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['BDE'],
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'MENUITEMS.LEAVES.TEXT',
    iconType: 'feather',
    icon: 'trello',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BDE'],
    submenu: [
      {
        path: '/client/myLeave',
        title: 'MENUITEMS.LEAVES.LIST.LEAVE-REQUESTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['BDE'],
        submenu: [],
      },
      {
        path: '/client/leave-balance',
        title: 'MENUITEMS.LEAVES.LIST.LEAVE-BALANCE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['BDE'],
        submenu: [],
      },
    ],
  },

  {
    path: '/client/attendance',
    title: 'MENUITEMS.EMPLOYEE.ATTENDANCE',
    iconType: 'feather',
    icon: 'edit',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BDE'],
    submenu: [],
  },

  // ADDED: View-only holidays for BDE
  {
    path: '/client/holidays',
    title: 'MENUITEMS.HOLIDAYS.TEXT',
    iconType: 'feather',
    icon: 'coffee',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BDE'],
    submenu: [],
  },

  {
    path: '/client/myteam',
    title: 'Team',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BDE'],
    submenu: [],
  },

  {
    path: '/client/daily-update',
    title: 'Daily Update',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BDE'],
    submenu: [],
  },

  {
    path: '/client/employee-updates',
    title: 'Employee Updates',
    iconType: 'feather',
    icon: 'activity',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BDE'],
    submenu: [],
  },

  {
    path: '',
    title: 'MENUITEMS.PAYROLL.TEXT',
    iconType: 'feather',
    icon: 'clipboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BDE'],
    submenu: [
      {
        path: '/client/payroll/employee-salary',
        title: 'MENUITEMS.PAYROLL.LIST.SALARY',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['BDE'],
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'Projects',
    iconType: 'feather',
    icon: 'book',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BDE'],
    submenu: [
      {
        path: '/client/projects/allProjects',
        title: 'All Projects',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['BDE'],
        submenu: [],
      },
      {
        path: '/client/projects/addProject',
        title: 'Add Project',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['BDE'],
        submenu: [],
      },
    ],
  },

  {
    path: '/client/alltasks',
    title: 'Tasks',
    iconType: 'feather',
    icon: 'command',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BDE'],
    submenu: [],
  },

  {
    path: '/client/performance',
    title: 'My Performance',
    iconType: 'feather',
    icon: 'bar-chart-2',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BDE'],
    submenu: [],
  },

  {
    path: '/client/my-targets',
    title: 'My Targets',
    iconType: 'feather',
    icon: 'target',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BDE'],
    submenu: [],
  },

  {
    path: '/client/daily-notes',
    title: 'Daily Client Notes',
    iconType: 'feather',
    icon: 'edit-3',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BDE'],
    submenu: [],
  },

  // ============================================================
  // BA MODULES
  // role = Employee
  // department = BA
  // ============================================================

  {
    // CHANGED: Was '/ba/dashboard/main' (admin dashboard route).
    // Now points to '/ba/dashboard' so BA sees the employee-style dashboard.
    // path: '/ba/dashboard/main', // OLD — admin dashboard
    path: '/ba/dashboard',
    title: 'Dashboard',
    iconType: 'feather',
    icon: 'monitor',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BA'],
    submenu: [],
  },

  {
    path: '',
    title: 'Clients',
    iconType: 'feather',
    icon: 'user',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BA'],
    submenu: [
      {
        path: '/ba/clients/all-clients',
        title: 'All Clients',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['BA'],
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'Leave Management',
    iconType: 'feather',
    icon: 'trello',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BA'],
    submenu: [
      {
        path: '/ba/myleaves',
        title: 'My Leaves',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['BA'],
        submenu: [],
      },
      {
        path: '/ba/myleaves/leave-balance',
        title: 'Leave Balance',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['BA'],
        submenu: [],
      },
    ],
  },

  {
    path: '/ba/attendance',
    title: 'Attendance',
    iconType: 'feather',
    icon: 'edit',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BA'],
    submenu: [],
  },

  // ADDED: View-only holidays for BA
  {
    path: '/ba/holidays',
    title: 'MENUITEMS.HOLIDAYS.TEXT',
    iconType: 'feather',
    icon: 'coffee',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BA'],
    submenu: [],
  },

  {
    path: '/ba/employees/allEmployees',
    title: 'Team',
    iconType: 'feather',
    icon: 'users',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BA'],
    submenu: [],
  },

  {
    path: '/ba/daily-update',
    title: 'Daily Update',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BA'],
    submenu: [],
  },

  {
    path: '/ba/employee-updates',
    title: 'Employee Updates',
    iconType: 'feather',
    icon: 'activity',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BA'],
    submenu: [],
  },

  {
    path: '/ba/payroll/employee-salary',
    title: 'Payroll',
    iconType: 'feather',
    icon: 'clipboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BA'],
    submenu: [],
  },

  {
    path: '',
    title: 'Projects',
    iconType: 'feather',
    icon: 'book',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BA'],
    submenu: [
      {
        path: '/ba/projects/allProjects',
        title: 'All Projects',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['BA'],
        submenu: [],
      },
      {
        path: '/ba/projects/addProject',
        title: 'Add Project',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Employee'],
        department: ['BA'],
        submenu: [],
      },
    ],
  },

  {
    path: '/ba/alltasks',
    title: 'Tasks',
    iconType: 'feather',
    icon: 'command',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    department: ['BA'],
    submenu: [],
  },

  // ============================================================
  // COMMON MODULES
  // ============================================================

  {
    path: '',
    title: 'Apps',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['Admin', 'Employee'],
    department: ['HR', 'BDE', 'BA', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },

  {
    path: 'calendar',
    title: 'Calendar',
    iconType: 'feather',
    icon: 'calendar',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: 'badge bg-blue sidebar-badge float-end',
    role: ['Admin', 'Employee'],
    department: ['HR', 'BDE', 'BA', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },

  {
    path: '/chat-window',
    title: 'Chat',
    iconType: 'feather',
    icon: 'message-square',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin', 'Employee'],
    department: ['HR', 'BDE', 'BA', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
    newTab: true,
  },

  {
    path: 'task',
    title: 'Task',
    iconType: 'feather',
    icon: 'check-circle',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin', 'Employee'],
    department: ['HR', 'BDE', 'BA', 'Backend Developer', 'Frontend Developer', 'Fullstack Developer', 'Graphic'],
    submenu: [],
  },
];